# Generated by Django 6.0.7 on 2026-07-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate_used', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('amount_base_currency', models.DecimalField(decimal_places=2, max_digits=12)),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('unequal', 'Unequal (explicit amounts)'), ('percentage', 'Percentage'), ('share', 'Share (weighted units)')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Entered manually'), ('import', 'Created from CSV import')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_paid', to='groups.groupmembership')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', max_length=3)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Entered manually'), ('import', 'Created from CSV import')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='groups.group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_paid', to='groups.groupmembership')),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_received', to='groups.groupmembership')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_splits', to='groups.groupmembership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('expense', 'member'), name='unique_split_per_member_per_expense')],
            },
        ),
    ]
