# Generated by Django 6.0.7 on 2026-07-09 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('scanning', 'Scanning'), ('pending_review', 'Pending review'), ('committed', 'Committed'), ('cancelled', 'Cancelled')], default='scanning', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='groups.group')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('resolved_data', models.JSONField(blank=True, null=True)),
                ('anomalies', models.JSONField(default=list)),
                ('proposed_action', models.CharField(choices=[('create_expense', 'Create expense'), ('create_settlement', 'Create settlement'), ('skip', 'Skip (duplicate)'), ('needs_manual_review', 'Needs manual review')], max_length=30)),
                ('resolution', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited and approved')], max_length=10, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importbatch')),
                ('resulting_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='expenses.expense')),
                ('resulting_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='expenses.settlement')),
            ],
            options={
                'ordering': ['row_number'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_row_number_per_batch')],
            },
        ),
    ]
